name: Delete Deployments

on:
  delete:
    branches-ignore:
      - main

jobs:
  delete:
    runs-on: ubuntu-latest
    steps:
      - uses: strumwolf/delete-deployment-environment@v2
        with:
          token: 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
          environment: github-pages
          onlyRemoveDeployments: true
